# Generated by Django 4.1.5 on 2023-01-20 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trivia', '0002_alter_winner_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='winner',
            name='points',
            field=models.IntegerField(),
        ),
    ]
